server:
  port: 9031

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
  datasource:
    url: jdbc:mysql://${PAGO_MS_DB_HOST}:${PAGO_MS_DB_PORT}/${PAGO_MS_DB_NAME}?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
    username: ${PAGO_MS_DB_USERNAME}
    password: ${PAGO_MS_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

eureka:
  client:
    service-url:
      defaultZone: http://registry-server:7081/eureka

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: never
  prometheus:
    metrics:
      export:
        enabled: true
